import { APMAgent } from "@jobsimi/apm";

class Agent {
  constructor() {
    this.apmAgent = new APMAgent();
  }
  async run(params, saveconfig) {
    console.log("Receive", params);

    const topic = params.topic;
    const outline = params.outline;

    const responseJSON = {};

    const output = { article: `THE FULL ARTICLE generated by OpenAI GPT-3` };

    this.apmAgent.saveOutput(saveconfig, output);

    return output;
  }
}

export { Agent };
